<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
<header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" href="/urls">Сайты</a>
                </li>

            </ul>
        </div>
    </nav>
</header>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Страница не найдена!</h1>
        <div class="row row-cols-1 row-cols-lg-1 align-items-lg-center">
            <div class="col">
                <img class="img-fluid" alt="404 error" src="/errors/404.svg" loading="lazy">
            </div>
            <div class="col">
                <h2 class="h2 mb-4">
                    Ошибка 404
                </h2>
                <p class="fs-5 text-black mb-3">Что это означает?</p>
                <p class="mb-4">Вы попали на страницу, которой не существует</p>
                <p class="fs-5 text-black mb-3">Почему это произошло?</p>
                <p class="mb-4">Запрошенная страница устарела, удалена или был введен не верный адрес в адресной строке</p>
                <p class="fs-5 text-black mb-3">Как исправить?</p>
                <p class="mb-2">Мы не знаем откуда Вы попали на эту страницу, поэтому рекомендуем начать <a href="/">с Главной</a></p>
            </div>
        </div>
    </div>
</main>

<footer class="border-top py-3 mt-5 flex-shrink-0">
    <div class="container-lg">
        <div class="text-center">
            <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
        </div>
    </div>
</footer>
</body>
</html>